apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-postgres
  template:
    metadata:
      labels:
        app: pokemon-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'pg_isready -U admin -d pokemon'
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'admin'
            - name: POSTGRES_PASSWORD
              value: 'admin'
            - name: POSTGRES_DB
              value: 'pokemon'
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pokemon-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-postgres-service
spec:
  selector:
    app: pokemon-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pokemon-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
